name: Python application

on: push

jobs:
  driver_load_info_env:
    environment: DB_SECRET
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        DB_SECRET_CODE: ${{ secrets.DB_SECRET_PASSWORD }} 
